version: "3.9"
services:

  half-life-2-dm:
    container_name: hl2dm
    image: troyfontaine/half-life2-dm-local:latest
    ports:
      - "27015:27015"
      - "27015:27015/udp"
      - "27020:27020/udp"
    env_file: custom/common.env
    volumes:
      - "${PWD}/custom/motd_default.txt:/home/steam/hl2mp-dedicated/tf/cfg/motd_default.txt"
