---
name: Merge Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  build_amd64:
    name: Build Code on AMD64 Architecture
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
